# Generated by Django 6.1.1 on 2026-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='External link to live app (e.g. http://blob:8000/)', null=True),
        ),
    ]
