# Generated by Django 6.1.1 on 2026-10-07 07:54

from django.db import migrations, models


def normalize_positions(apps, schema_editor):
    project = apps.get_model('projects', 'Project')
    manager = project.objects.using(schema_editor.connection.alias)
    for is_featured in [False, True]:
        items = list(manager.filter(is_featured=is_featured))
        for position, item in enumerate(items, start=1):
            item.order = position
        manager.bulk_update(items, ['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in this section, starting at 1. Use 0 to place it last. Other items shift automatically.'),
        ),
        migrations.RunPython(normalize_positions, migrations.RunPython.noop),
    ]
