# Generated by Django 6.1.1 on 2026-09-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='works',
            field=models.TextField(blank=True),
        ),
    ]
