# Generated by Django 6.1.1 on 2026-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_is_primary_teammember_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='group',
            field=models.CharField(choices=[('leadership', 'Leadership'), ('members', 'Members')], default='members', max_length=20),
        ),
    ]
