# Generated by Django 6.1.1 on 2026-09-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_seed_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
    ]
