# Generated by Django 6.1.1 on 2026-09-30 11:16

from django.db import migrations, models


def set_second_contacts(apps, schema_editor):
    # Fill the secondary contacts (matching the original static Contact page)
    # on the single SiteSettings row, whether it was seeded or created by hand.
    SiteSettings = apps.get_model("home", "SiteSettings")
    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            "email_2": "pivotrisks@gmail.com",
            "phone_2": "+977 9851099693",
        },
    )


def clear_second_contacts(apps, schema_editor):
    SiteSettings = apps.get_model("home", "SiteSettings")
    SiteSettings.objects.filter(pk=1).update(email_2="", phone_2="")


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_seed_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(set_second_contacts, clear_second_contacts),
    ]
