# Generated by Django 6.1.1 on 2026-10-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sitesettings_email_2_sitesettings_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.TextField(blank=True),
        ),
    ]
