# Generated by Django 6.1.1 on 2026-10-01 07:18

from django.db import migrations, models


def seed_departments(apps, schema_editor):
    # Create the three department rows (contacts filled in via the admin).
    DepartmentContact = apps.get_model("home", "DepartmentContact")
    departments = [
        "Finance / HR",
        "Survey",
        "Actuarial / Risk Management",
    ]
    for order, name in enumerate(departments, start=1):
        DepartmentContact.objects.get_or_create(department=name, defaults={"order": order})


def unseed_departments(apps, schema_editor):
    apps.get_model("home", "DepartmentContact").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sitesettings_site_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'department'],
            },
        ),
        migrations.RunPython(seed_departments, unseed_departments),
    ]
