# Generated by Django 6.1.1 on 2026-10-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_departmentcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentContact',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='actuarial_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='actuarial_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='finance_hr_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='finance_hr_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='survey_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='survey_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
