# Generated by Django 6.1.1 on 2026-10-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_departmentcontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_2',
        ),
    ]
