# Generated by Django 6.1.1 on 2026-10-01 07:59

from django.db import migrations, models


def restore_general_contacts(apps, schema_editor):
    # Restore the general contact values on the single settings row
    # (they were dropped by 0012, which only the footer needed).
    SiteSettings = apps.get_model("home", "SiteSettings")
    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            "email": "info@pivotrisks.com",
            "phone": "+977 9843653691",
            "email_2": "pivotrisks@gmail.com",
            "phone_2": "+977 9851099693",
        },
    )


def clear_general_contacts(apps, schema_editor):
    SiteSettings = apps.get_model("home", "SiteSettings")
    SiteSettings.objects.filter(pk=1).update(email="", phone="", email_2="", phone_2="")


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(restore_general_contacts, clear_general_contacts),
    ]
