# Generated by Django 6.1.1 on 2026-10-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sitesettings_contact_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
    ]
