# Generated by Django 6.1.1 on 2026-10-07 07:54

from django.db import migrations, models


def normalize_positions(apps, schema_editor):
    for name, scope_field in [('Service', 'is_primary'), ('TeamMember', 'group')]:
        model = apps.get_model('home', name)
        manager = model.objects.using(schema_editor.connection.alias)
        scopes = manager.order_by().values_list(scope_field, flat=True).distinct()
        for scope in list(scopes):
            items = list(manager.filter(**{scope_field: scope}).order_by(*model._meta.ordering, 'pk'))
            for position, item in enumerate(items, start=1):
                item.order = position
            manager.bulk_update(items, ['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_notice_image_notice_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in this section, starting at 1. Use 0 to place it last. Other items shift automatically.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in this section, starting at 1. Use 0 to place it last. Other items shift automatically.'),
        ),
        migrations.RunPython(normalize_positions, migrations.RunPython.noop),
    ]
